CREATE TABLE `expansion_budget` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fiscalQuarter` varchar(10) NOT NULL,
	`fiscalYear` int NOT NULL,
	`totalBudget` int NOT NULL,
	`marketResearchBudget` int NOT NULL,
	`regulatoryComplianceBudget` int NOT NULL,
	`driverRecruitmentBudget` int NOT NULL,
	`marketingBudget` int NOT NULL,
	`technologyBudget` int NOT NULL,
	`contingencyBudget` int NOT NULL,
	`totalSpent` int NOT NULL DEFAULT 0,
	`marketResearchSpent` int NOT NULL DEFAULT 0,
	`regulatoryComplianceSpent` int NOT NULL DEFAULT 0,
	`driverRecruitmentSpent` int NOT NULL DEFAULT 0,
	`marketingSpent` int NOT NULL DEFAULT 0,
	`technologySpent` int NOT NULL DEFAULT 0,
	`contingencySpent` int NOT NULL DEFAULT 0,
	`rolloverFromPrevious` int NOT NULL DEFAULT 0,
	`approvedByProposalId` int,
	`approvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expansion_budget_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `expansion_launches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`marketId` int NOT NULL,
	`launchName` varchar(200) NOT NULL,
	`launchTier` enum('tier1','tier2','tier3') NOT NULL,
	`currentPhase` enum('planning','regulatory_compliance','technology_localization','driver_recruitment','closed_beta','soft_launch','public_launch','growth','maturity') NOT NULL DEFAULT 'planning',
	`plannedBetaDate` timestamp,
	`plannedSoftLaunchDate` timestamp,
	`plannedPublicLaunchDate` timestamp,
	`actualBetaDate` timestamp,
	`actualSoftLaunchDate` timestamp,
	`actualPublicLaunchDate` timestamp,
	`approvedBudget` int NOT NULL,
	`spentToDate` int NOT NULL DEFAULT 0,
	`projectedFinalCost` int,
	`targetDriverCount` int NOT NULL,
	`targetRideCount` int NOT NULL,
	`targetMarketShare` int,
	`currentDriverCount` int NOT NULL DEFAULT 0,
	`currentRideCount` int NOT NULL DEFAULT 0,
	`currentMarketShare` int,
	`averageRating` int,
	`averageWaitTime` int,
	`acceptanceRate` int,
	`cancellationRate` int,
	`totalRevenue` int NOT NULL DEFAULT 0,
	`totalDriverPayments` int NOT NULL DEFAULT 0,
	`contributionMargin` int,
	`isBreakeven` boolean NOT NULL DEFAULT false,
	`breakEvenDate` timestamp,
	`status` enum('active','on_hold','delayed','completed','cancelled') NOT NULL DEFAULT 'active',
	`healthScore` int,
	`launchLeadId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expansion_launches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `launch_milestones` (
	`id` int AUTO_INCREMENT NOT NULL,
	`launchId` int NOT NULL,
	`milestoneName` varchar(200) NOT NULL,
	`description` text,
	`category` enum('regulatory','technology','recruitment','marketing','operations','financial') NOT NULL,
	`plannedDate` timestamp,
	`actualDate` timestamp,
	`daysDelayed` int,
	`status` enum('not_started','in_progress','blocked','completed','cancelled') NOT NULL DEFAULT 'not_started',
	`blockerReason` text,
	`assignedTo` int,
	`dependsOn` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `launch_milestones_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `market_analysis_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`marketId` int NOT NULL,
	`reportType` enum('preliminary_assessment','deep_dive_analysis','competitive_analysis','regulatory_assessment','financial_projection') NOT NULL,
	`reportVersion` int NOT NULL DEFAULT 1,
	`executiveSummary` text,
	`fullReportUrl` text,
	`fullReportJson` text,
	`keyFindings` text,
	`opportunities` text,
	`risks` text,
	`recommendations` text,
	`dataSources` text,
	`dataQuality` enum('high','medium','low'),
	`analyzedBy` varchar(100),
	`reviewedBy` int,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedAt` timestamp,
	`approvedAt` timestamp,
	CONSTRAINT `market_analysis_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `market_opportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(100),
	`country` varchar(100) NOT NULL,
	`countryCode` varchar(2) NOT NULL,
	`region` varchar(100),
	`tier` enum('tier1','tier2','tier3','watch') NOT NULL,
	`overallScore` int NOT NULL,
	`marketAttractivenessScore` int NOT NULL,
	`competitiveLandscapeScore` int NOT NULL,
	`regulatoryFeasibilityScore` int NOT NULL,
	`operationalReadinessScore` int NOT NULL,
	`population` int,
	`metroPopulation` int,
	`gdpPerCapita` int,
	`smartphonePenetration` int,
	`rideshareAdoptionRate` int,
	`vehicleOwnershipRate` int,
	`competitorCount` int DEFAULT 0,
	`marketLeader` varchar(100),
	`marketLeaderShare` int,
	`marketSaturation` int,
	`averageRidePrice` int,
	`regulatoryStatus` enum('permissive','moderate','restrictive','unclear','prohibited'),
	`licenseRequired` boolean DEFAULT true,
	`estimatedComplianceTime` int,
	`estimatedComplianceCost` int,
	`estimatedTAM` int,
	`estimatedRevenue` int,
	`estimatedBreakEvenMonths` int,
	`estimatedROI` int,
	`aiAnalysisSummary` text,
	`aiRecommendation` enum('immediate_evaluation','evaluate_within_6mo','monitor','not_viable') NOT NULL,
	`aiConfidenceScore` int NOT NULL,
	`status` enum('identified','preliminary_assessment','deep_dive_analysis','dao_proposal','approved','rejected','launched') NOT NULL DEFAULT 'identified',
	`lastAnalyzedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `market_opportunities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `market_performance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`launchId` int NOT NULL,
	`periodType` enum('daily','weekly','monthly','quarterly') NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`activeDrivers` int NOT NULL,
	`newDriversAdded` int DEFAULT 0,
	`driversChurned` int DEFAULT 0,
	`driverRetentionRate` int,
	`averageDriverEarnings` int,
	`driverSatisfactionScore` int,
	`totalRides` int NOT NULL,
	`uniqueRiders` int NOT NULL,
	`newRiders` int DEFAULT 0,
	`ridersChurned` int DEFAULT 0,
	`riderRetentionRate` int,
	`averageRidesPerRider` int,
	`riderSatisfactionScore` int,
	`averageWaitTime` int NOT NULL,
	`acceptanceRate` int NOT NULL,
	`cancellationRate` int NOT NULL,
	`averageRating` int NOT NULL,
	`technicalErrorRate` int,
	`grossRevenue` int NOT NULL,
	`netRevenue` int NOT NULL,
	`driverPayments` int NOT NULL,
	`insuranceFees` int NOT NULL,
	`marketingSpend` int NOT NULL,
	`operatingExpenses` int NOT NULL,
	`contributionMargin` int NOT NULL,
	`contributionMarginPercent` int,
	`ebitda` int,
	`estimatedMarketShare` int,
	`competitorPriceIndex` int,
	`rideGrowthRate` int,
	`revenueGrowthRate` int,
	`healthScore` int NOT NULL,
	`healthTrend` enum('improving','stable','declining'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `market_performance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `regulatory_requirements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`marketId` int NOT NULL,
	`requirementType` enum('platform_license','driver_license','vehicle_inspection','insurance','background_check','data_privacy','tax_registration','accessibility','other') NOT NULL,
	`requirementName` varchar(200) NOT NULL,
	`description` text,
	`jurisdictionLevel` enum('federal','state','municipal') NOT NULL,
	`jurisdictionName` varchar(100) NOT NULL,
	`isRequired` boolean NOT NULL DEFAULT true,
	`estimatedCost` int,
	`estimatedTimeToComplete` int,
	`renewalFrequency` varchar(50),
	`regulationUrl` text,
	`applicationUrl` text,
	`guidanceNotes` text,
	`status` enum('identified','in_progress','submitted','approved','rejected','not_applicable') NOT NULL DEFAULT 'identified',
	`assignedTo` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `regulatory_requirements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `expansion_launches` ADD CONSTRAINT `expansion_launches_marketId_market_opportunities_id_fk` FOREIGN KEY (`marketId`) REFERENCES `market_opportunities`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `expansion_launches` ADD CONSTRAINT `expansion_launches_launchLeadId_users_id_fk` FOREIGN KEY (`launchLeadId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `launch_milestones` ADD CONSTRAINT `launch_milestones_launchId_expansion_launches_id_fk` FOREIGN KEY (`launchId`) REFERENCES `expansion_launches`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `launch_milestones` ADD CONSTRAINT `launch_milestones_assignedTo_users_id_fk` FOREIGN KEY (`assignedTo`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `market_analysis_reports` ADD CONSTRAINT `market_analysis_reports_marketId_market_opportunities_id_fk` FOREIGN KEY (`marketId`) REFERENCES `market_opportunities`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `market_analysis_reports` ADD CONSTRAINT `market_analysis_reports_reviewedBy_users_id_fk` FOREIGN KEY (`reviewedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `market_analysis_reports` ADD CONSTRAINT `market_analysis_reports_approvedBy_users_id_fk` FOREIGN KEY (`approvedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `market_performance` ADD CONSTRAINT `market_performance_launchId_expansion_launches_id_fk` FOREIGN KEY (`launchId`) REFERENCES `expansion_launches`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `regulatory_requirements` ADD CONSTRAINT `regulatory_requirements_marketId_market_opportunities_id_fk` FOREIGN KEY (`marketId`) REFERENCES `market_opportunities`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `regulatory_requirements` ADD CONSTRAINT `regulatory_requirements_assignedTo_users_id_fk` FOREIGN KEY (`assignedTo`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;